server.tomcat.accesslog.enabled = true

spring.datasource.url = jdbc:postgresql://dpg-d8sm6n68bjmc738i9ck0-a.frankfurt-postgres.render.com/postgresql_rssreader2_e7xh
spring.datasource.username = postgresql_rssreader2_e7xh_user
spring.datasource.password = 2SY8f4QPtENwi8h8r5QMTTSlkv2ymDA6

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.open-in-view=false

logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true