server.tomcat.accesslog.enabled = true

spring.datasource.url = jdbc:postgresql://dpg-d3466k7fte5s73eglkgg-a.frankfurt-postgres.render.com/postgresql_rssreader2
spring.datasource.username = postgresql_rssreader2_user
spring.datasource.password = JWp2N97TF7SOCkhvmQ3v3h4fS9bujq5l

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.open-in-view=false

logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true